package com.yetanalytics.hlaxapi.cache;

import java.util.List;
import java.util.Optional;

final class PostgresqlObjectCacheQueries implements ObjectCacheQueries {

    private final String quotedSchema;

    PostgresqlObjectCacheQueries(String schema) {
        this.quotedSchema = "\"" + schema + "\"";
    }

    @Override
    public int binaryJdbcType() {
        return java.sql.Types.BINARY;
    }

    @Override
    public List<String> connectionSetupStatements() {
        return List.of(
                "CREATE SCHEMA IF NOT EXISTS " + quotedSchema,
                "SET search_path TO " + quotedSchema);
    }

    @Override
    public List<String> resetSchemaStatements() {
        return List.of(
                "DROP TABLE IF EXISTS object_attribute_current",
                "DROP TABLE IF EXISTS object_instance",
                "DROP TABLE IF EXISTS fom_attribute",
                "DROP TABLE IF EXISTS fom_object_class",
                "DROP TABLE IF EXISTS object_cache_metadata");
    }

    @Override
    public List<String> createSchemaStatements() {
        return List.of(
                """
                CREATE TABLE object_cache_metadata (
                    schema_version INTEGER NOT NULL
                )
                """,
                """
                CREATE TABLE fom_object_class (
                    id INTEGER PRIMARY KEY,
                    hla_name TEXT NOT NULL,
                    local_name TEXT NOT NULL UNIQUE,
                    parent_name TEXT
                )
                """,
                """
                CREATE TABLE fom_attribute (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    class_id INTEGER NOT NULL REFERENCES fom_object_class(id),
                    attribute_name TEXT NOT NULL,
                    path_key TEXT NOT NULL,
                    data_type TEXT NOT NULL,
                    primitive_type TEXT,
                    is_leaf INTEGER NOT NULL,
                    UNIQUE(class_id, path_key)
                )
                """,
                """
                CREATE TABLE object_instance (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    object_handle TEXT NOT NULL UNIQUE,
                    object_name TEXT,
                    class_id INTEGER NOT NULL REFERENCES fom_object_class(id),
                    discovered_at TEXT NOT NULL,
                    removed_at TEXT
                )
                """,
                """
                CREATE TABLE object_attribute_current (
                    instance_id BIGINT NOT NULL REFERENCES object_instance(id),
                    attribute_id INTEGER NOT NULL REFERENCES fom_attribute(id),
                    value_type TEXT NOT NULL,
                    value_blob BYTEA,
                    value_json TEXT,
                    raw_bytes BYTEA,
                    observed_at TEXT NOT NULL,
                    sequence BIGINT NOT NULL,
                    PRIMARY KEY(instance_id, attribute_id)
                )
                """,
                "CREATE UNIQUE INDEX idx_object_handle ON object_instance(object_handle)",
                "CREATE INDEX idx_fom_attribute_class_path ON fom_attribute(class_id, path_key)");
    }

    @Override
    public String insertSchemaVersion() {
        return "INSERT INTO object_cache_metadata (schema_version) VALUES (?)";
    }

    @Override
    public String insertClass() {
        return """
                INSERT INTO fom_object_class (id, hla_name, local_name, parent_name)
                VALUES (?, ?, ?, ?)
                ON CONFLICT(id) DO NOTHING
                """;
    }

    @Override
    public String insertAttribute() {
        return """
                INSERT INTO fom_attribute
                    (id, class_id, attribute_name, path_key, data_type, primitive_type, is_leaf)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(id) DO NOTHING
                """;
    }

    @Override
    public Optional<String> afterSeedFomMetadata() {
        return Optional.of("""
                SELECT setval(
                    pg_get_serial_sequence('fom_attribute', 'id'),
                    COALESCE((SELECT MAX(id) FROM fom_attribute), 1),
                    true)
                """);
    }

    @Override
    public String upsertObject() {
        return """
                INSERT INTO object_instance (object_handle, object_name, class_id, discovered_at)
                VALUES (?, ?, ?, ?)
                ON CONFLICT(object_handle) DO UPDATE SET
                    object_name = COALESCE(excluded.object_name, object_instance.object_name),
                    class_id = excluded.class_id,
                    removed_at = NULL
                """;
    }

    @Override
    public String loadObject() {
        return "SELECT id, object_name FROM object_instance WHERE object_handle = ?";
    }

    @Override
    public String removeObject() {
        return "UPDATE object_instance SET removed_at = ? WHERE object_handle = ?";
    }

    @Override
    public String findCurrentValue() {
        return """
                SELECT c.value_type, c.value_json, c.value_blob, c.raw_bytes
                FROM object_attribute_current c
                JOIN fom_attribute a ON a.id = c.attribute_id
                WHERE c.instance_id = ? AND (a.path_key = ? OR a.path_key = ?)
                ORDER BY CASE WHEN a.path_key = ? THEN 0 ELSE 1 END
                LIMIT 1
                """;
    }

    @Override
    public String findObjectId() {
        return "SELECT id FROM object_instance WHERE object_handle = ?";
    }

    @Override
    public String listCurrentObjects() {
        return """
                SELECT id, object_handle, object_name
                FROM object_instance
                WHERE class_id = ? AND removed_at IS NULL
                ORDER BY id
                """;
    }

    @Override
    public String deleteCurrentValues() {
        return """
                DELETE FROM object_attribute_current
                WHERE instance_id = ?
                    AND attribute_id IN (
                        SELECT id
                        FROM fom_attribute
                        WHERE class_id = ? AND attribute_name = ?
                    )
                """;
    }

    @Override
    public String upsertCurrentValue() {
        return """
                INSERT INTO object_attribute_current
                    (instance_id, attribute_id, value_type, value_blob, value_json, raw_bytes, observed_at, sequence)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(instance_id, attribute_id) DO UPDATE SET
                    value_type = excluded.value_type,
                    value_blob = excluded.value_blob,
                    value_json = excluded.value_json,
                    raw_bytes = excluded.raw_bytes,
                    observed_at = excluded.observed_at,
                    sequence = excluded.sequence
                """;
    }

    @Override
    public String insertDynamicAttribute() {
        return """
                INSERT INTO fom_attribute
                    (class_id, attribute_name, path_key, data_type, primitive_type, is_leaf)
                VALUES (?, ?, ?, ?, ?, ?)
                ON CONFLICT(class_id, path_key) DO NOTHING
                """;
    }

    @Override
    public String findAttributeId() {
        return "SELECT id FROM fom_attribute WHERE class_id = ? AND path_key = ?";
    }
}
